### ISSUE TITLE
Unit label not shown

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis-app-lifecycle#39]
### How to Reproduce
Go to lifecycle app with lifecycle data
Select core variable
Look at card

### Expected behavior
![screen shot 2018-09-07 at 12 53 01](https://user-images.githubusercontent.com/10075439/45215199-04816a80-b29d-11e8-815f-e9ae8ac71d0f.png)

### Observed behavior
![screen shot 2018-09-07 at 12 53 16](https://user-images.githubusercontent.com/10075439/45215205-077c5b00-b29d-11e8-8c37-c3c2314ab3c7.png)

**Comment by sidohaakma** [comment]
Fixed by #41
