### ISSUE TITLE
Cannot open menu item with many variables

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis-app-lifecycle#49]
### How to Reproduce
Go to https://molgenis88.gcc.rug.nl/menu/main/app-molgenis-app-lifecycle
Open Child
Open Health-relateed characteristics
Click on Child's height

### Expected behavior
Lifecycle variables open

### Observed behavior
It takes a very long time for the lifecycle variables to be filled with information, your browser might even freeze during the process. 

Same goes for when you click "Harmonizations"

**Comment by fdlk** [comment]
Taken a look, there are 432 variables for child height and it takes 10 seconds to retrieve the 20MB with their results
